"""The repo's own documents, checked for the ways they rot silently.

DESIGN.md's decision log is appended to a row at a time, by an agent, on the day
the decision is made. That is the whole point of it — and it means the file's
structure is maintained by whoever is least likely to re-read the file. A stray
blank line between two rows ends the markdown table and starts a new one, which
costs nothing to write, renders wrong everywhere the file is read, and shows up
in no test and no diff review. It has happened. So it is pinned here.

The published demo is here for the same reason. It is a build product — bind,
render, copy over `site/demo.html` — regenerated by hand whenever the renderer
moves, so the properties it is *supposed* to demonstrate are exactly the ones a
regeneration can quietly lose.
"""

from __future__ import annotations

import pathlib
import re

REPO = pathlib.Path(__file__).resolve().parent.parent
DESIGN = REPO / "DESIGN.md"
DEMO = REPO / "site" / "demo.html"

ROW = re.compile(r"^\| (\d{4}-\d{2}-\d{2}) \|")


def _decision_log() -> list[str]:
    """The decision table's lines, from its header to the blank line that ends it."""
    lines = DESIGN.read_text(encoding="utf-8").split("\n")
    start = next(i for i, line in enumerate(lines) if line.startswith("| Date |"))
    end = next(i for i in range(start, len(lines)) if not lines[i].strip())
    return lines[start:end]


def test_the_decision_log_is_one_unbroken_table() -> None:
    """Every dated row sits in the table, not in one of two tables."""
    dated = [line for line in DESIGN.read_text(encoding="utf-8").split("\n") if ROW.match(line)]
    assert dated, "the decision log has no rows"
    # The table is its header, its separator, then one row per decision.
    assert len(_decision_log()) - 2 == len(dated), (
        "a dated row falls outside the decision table — a blank line between two "
        "rows splits it in two, and markdown renders the second half as a new table"
    )


def test_the_decision_log_reads_oldest_first() -> None:
    """Appended daily, so out-of-order means a row landed in the wrong place."""
    dates = [match.group(1) for line in _decision_log() if (match := ROW.match(line))]
    assert dates == sorted(dates), "decision rows are out of date order"


# ---- the published demo shows a web citation, and shows it not drifting ------

SOURCE_LIST = re.compile(r'<ul(?: class="srclist")?>(<li><span class="doc">.*?)</ul>')


def _source_lists() -> list[str]:
    """The rail's source list and the end matter's — the two places sources are named."""
    return SOURCE_LIST.findall(DEMO.read_text(encoding="utf-8"))


def test_the_demo_names_three_sources_one_of_them_a_dated_link() -> None:
    """A reader evaluating backdraft cannot see that a web citation is a citation
    like any other unless the one artifact anybody looks at carries one."""
    listings = _source_lists()
    assert len(listings) == 2, "expected the rail's source list and the end matter's"
    for listing in listings:
        assert listing.count("<li>") == 3, "the demo should cite three sources"
        assert re.search(
            r'<a class="origin" href="https://en\.wikipedia\.org/[^"]+">'
            r"[^<]+</a> &middot; fetched \d{4}-\d{2}-\d{2}",
            listing,
        ), "the fetched source should show a live link and its fetch date"


def test_the_demos_web_citation_names_a_fixed_revision() -> None:
    """`?oldid=` is why a re-bind months from now still says `resolved`. Re-fetch
    the live article instead and the front page shows `drifted` within days,
    which teaches that the tool is broken rather than that the source moved."""
    for listing in _source_lists():
        url = re.search(r'href="(https://en\.wikipedia\.org/[^"]+)"', listing)
        assert url is not None
        assert "oldid=" in url.group(1), (
            "the demo must cite Wikipedia's permanent link, not the live article"
        )


def test_the_demo_titles_the_fetched_source_by_its_slug() -> None:
    """`fetch.filename_for` stages the permanent link as `index.html`; a source
    called "Index" in the shop window is the invented name winning."""
    for listing in _source_lists():
        assert '<span class="doc">Franklin County</span>' in listing
        assert "index.html" not in listing
